#!/usr/bin/env python3
"""
Benchmark comparison of SPX IV surface forecasting models.

Scope: the tuned models for the c63/h21/precovid/level task —
DLinear, HOT (kronecker_product + kronecker_sum), DynGWN, PatchTST
(patch3 + patch7) — plus a built-in persistence baseline. Each HOT and
PatchTST variant is reported as its own row.

For every model the result dir is resolved by reading its tuning
leaderboard and picking the combo with the lowest `best_val_loss` that
has both `config.json` and `best_model.pt` on disk.

Once a directory is chosen, if `pred.npy` is present it is loaded as-is.
Otherwise it is regenerated by running
    `<regen_script> --predict_only --out_dir <dir> --batch_size <INFER_BATCH>`
which reads config.json + best_model.pt and writes pred.npy alongside.
The default INFER_BATCH is 32 — this matches local capacity, regardless of
the (typically larger) batch size used during Colab training.

All model scripts denormalize predictions to ORIGINAL target-space units
(raw IV for level; raw log-diff for logdiff) before saving pred.npy. The
reference trues built here live in the same space, so all metrics below are
in original target-space units (vol-points for level).

Each model's start_dates.npy aligns its windows to the reference test set;
mismatched window counts surface as a loud date-alignment failure.

Persistence baseline: built fresh from the CSV inside `build_reference()`
(`Persist(ref)` row in the table). Not a separate model entry.

Per-model side-effect: `metrics_test.json` is written into each model's
result dir alongside pred.npy, so a single model's scores can be inspected
without rebuilding the whole table.

Metrics (all in original target-space units):
  mse, rmse, mae, rse  standard regression metrics
  bias                 mean signed error; positive = over-prediction
  da                   directional accuracy: fraction where sign(pred)==sign(true)
  ic_mean, ic_std      Spearman rank-IC across (window, step) over N_IV features.
                       target_space=level   : computed on (pred-origin) vs (true-origin),
                                              i.e. ranks cells by forecast change. Persist(ref)
                                              → ic = NaN by construction.
                       target_space=logdiff : computed on raw pred vs true (logdiffs are
                                              already changes), i.e. ranks cells by today's
                                              log-return. Persist(ref) gives a real number.

LSTS components (from lsts_loss.py — surface-shape losses on the IV grid):
  lsts_level          MSE of surface-mean (overall level offset)
  lsts_skew           MSE of moneyness slope (smile shape)
  lsts_term           MSE of tau slope (term-structure shape)
  lsts_curvature      MSE of moneyness 2nd difference (curvature)

Outputs saved to --out_dir (default: comparison_results/):
  {dataset}_{ts}_*.csv             timestamped overall metrics
  latest_{tag}.csv                 always overwritten with most recent run
  latest_horizons_{tag}.csv        per-horizon ic / mse / mae / lsts_* per model
  latest_summary_{tag}.json        machine-readable summary
"""

import argparse
import glob
import json
import os
import subprocess
import sys
import warnings
from datetime import datetime

import numpy as np
import pandas as pd
import torch
from scipy.stats import spearmanr, ConstantInputWarning

from lsts_loss import compute_lsts_components

# ─── Constants ────────────────────────────────────────────────────────────────

DEFAULT_SEQ_LEN      = 63
DEFAULT_PRED_LEN     = 21
DEFAULT_DATASET      = "precovid"
DEFAULT_TARGET_SPACE = "level"
DEFAULT_INFER_BATCH  = 32           # local-friendly inference batch
TRAIN_FRAC           = 0.70
TEST_FRAC            = 0.20
PRECOVID_END         = "2019-12-31"
DATASET_CHOICES      = ["full", "precovid"]
TARGET_SPACE_CHOICES = ["level", "logdiff"]
REPORT_HORIZONS      = [1, 5, 10, 21, 42, 63]   # filtered to ≤ pred_len

# ─── Model registry ───────────────────────────────────────────────────────────
# Each entry has either a `tuning_dir` (single leaderboard.csv; resolver picks
# the lowest-`best_val_loss` combo from that sweep) or a `result_dir` glob
# (used for non-tuned baselines like VAR — pick the most-recently-modified
# matching dir).

def build_models(dataset: str, target_space: str,
                 seq_len: int, pred_len: int) -> list[dict]:
    tag = f"{dataset}_{target_space}_SPX_IV_{seq_len}_{pred_len}"
    return [
        {
            "name":         "VAR(BIC)",
            "result_dir":   f"VAR/results/{tag}_VAR_p*_bic",
            "regen_script": "VAR/var_spx_iv.py",
            "loader":       "flat",
        },
        {
            "name":         "DLinear",
            "tuning_dir":   f"DLinear/tuning_results/{tag}",
            "result_dir":   f"DLinear/results/{tag}_DLinear_*",
            "regen_script": "DLinear/dlinear.py",
            "loader":       "flat",
        },
        {
            "name":         "HOT(product)",
            "tuning_dir":   f"HOT/tuning_results/{tag}/kronecker_product",
            "result_dir":   f"HOT/results/{tag}_HOT_*kronecker_product*",
            "regen_script": "HOT/hot.py",
            "loader":       "hot",
        },
        {
            "name":         "HOT(sum)",
            "tuning_dir":   f"HOT/tuning_results/{tag}/kronecker_sum",
            "result_dir":   f"HOT/results/{tag}_HOT_*kronecker_sum*",
            "regen_script": "HOT/hot.py",
            "loader":       "hot",
        },
        {
            "name":         "DynGWN",
            "tuning_dir":   f"DynGWN/tuning_results/{tag}/grid_plus_adaptive",
            "result_dir":   f"DynGWN/results/{tag}_DynGWN_*",
            "regen_script": "DynGWN/dyngwn.py",
            "loader":       "flat",
        },
        {
            "name":         "PatchTST(patch3)",
            "tuning_dir":   f"PatchTST/tuning_results/{tag}/patch3",
            "result_dir":   f"PatchTST/results/{tag}_PatchTST_pl3_*",
            "regen_script": "PatchTST/patchtst.py",
            "loader":       "flat",
        },
        {
            "name":         "PatchTST(patch7)",
            "tuning_dir":   f"PatchTST/tuning_results/{tag}/patch7",
            "result_dir":   f"PatchTST/results/{tag}_PatchTST_pl7_*",
            "regen_script": "PatchTST/patchtst.py",
            "loader":       "flat",
        },
    ]


# ─── Ground truth ─────────────────────────────────────────────────────────────

def _slice_dataset(df: pd.DataFrame, dataset: str) -> pd.DataFrame:
    if dataset == "full":
        return df
    if dataset == "precovid":
        end = pd.Timestamp(PRECOVID_END)
        return df[df["date"] <= end].reset_index(drop=True)
    raise ValueError(f"Unknown dataset {dataset!r}; choose from {DATASET_CHOICES}")


def _apply_target_space(iv_raw: np.ndarray, dates_full: np.ndarray, target_space: str):
    """level → unchanged; logdiff → log(IV)[1:]-log(IV)[:-1], dates trimmed by 1."""
    if target_space == "level":
        return iv_raw, dates_full
    if target_space == "logdiff":
        if (iv_raw <= 0).any():
            raise ValueError("logdiff target_space requires all IV > 0")
        log_iv = np.log(iv_raw)
        return (log_iv[1:] - log_iv[:-1]).astype(iv_raw.dtype), dates_full[1:]
    raise ValueError(f"Unknown target_space {target_space!r}; choose from {TARGET_SPACE_CHOICES}")


def _parse_grid(iv_cols: list[str]) -> tuple[np.ndarray, np.ndarray]:
    """
    Parse iv_{moneyness}_{tau} columns. Returns (moneyness, tau) as float
    arrays. CSV column order is (tau outer, moneyness inner): col k =
    i_t·n_moneyness + i_m. This makes a C-order reshape from [..., n_iv]
    to [..., n_tau, n_moneyness] place tau on axis -2 and moneyness on
    axis -1, matching the LSTS convention `(..., n_tau, n_k)`.
    """
    moneyness_strs, tau_strs = [], []
    for c in iv_cols:
        rest = c[len("iv_"):]
        m, t = rest.rsplit("_", 1)
        if m not in moneyness_strs:
            moneyness_strs.append(m)
        if t not in tau_strs:
            tau_strs.append(t)
    moneyness = np.array([float(m) for m in moneyness_strs], dtype=np.float32)
    tau       = np.array([float(t) for t in tau_strs],       dtype=np.float32)
    n_m, n_t = len(moneyness), len(tau)
    if n_m * n_t != len(iv_cols):
        raise ValueError(f"iv_ columns are not a complete grid: "
                         f"{n_m} moneyness × {n_t} tau ≠ {len(iv_cols)}")
    return moneyness, tau


def build_reference(csv_path: str, dataset: str, target_space: str,
                    seq_len: int, pred_len: int):
    df = pd.read_csv(csv_path, low_memory=False)
    df["date"] = pd.to_datetime(df["date"])
    df = _slice_dataset(df, dataset)

    iv_cols = [c for c in df.columns if c.startswith("iv_")]
    if not iv_cols:
        raise ValueError(f"No iv_* columns found in {csv_path}")
    n_iv = len(iv_cols)
    moneyness, tau = _parse_grid(iv_cols)
    n_moneyness, n_tau = len(moneyness), len(tau)

    iv_raw     = df[iv_cols].to_numpy(dtype=np.float32)
    dates_full = df["date"].to_numpy(dtype="datetime64[D]")
    data, all_dates = _apply_target_space(iv_raw, dates_full, target_space)

    T = len(data)
    num_train = int(T * TRAIN_FRAC)
    num_test  = int(T * TEST_FRAC)
    num_val   = T - num_train - num_test

    test_start = T - num_test - seq_len

    test_slice      = data[test_start:].astype(np.float32)
    test_date_slice = all_dates[test_start:]

    n = len(test_slice) - seq_len - pred_len + 1
    trues   = np.empty((n, pred_len, n_iv), dtype=np.float32)
    persist = np.empty((n, pred_len, n_iv), dtype=np.float32)
    ref_dates = np.empty(n, dtype="datetime64[D]")

    for i in range(n):
        trues[i] = test_slice[i + seq_len : i + seq_len + pred_len]
        if target_space == "logdiff":
            persist[i] = 0.0
        else:
            persist[i] = test_slice[i + seq_len - 1]
        ref_dates[i] = test_date_slice[i + seq_len]

    meta = {
        "T": T, "num_train": num_train, "num_val": num_val, "num_test": num_test,
        "n_iv": n_iv, "n_test": n,
        "n_moneyness": n_moneyness, "n_tau": n_tau,
        "moneyness": moneyness, "tau": tau,
        "seq_len": seq_len, "pred_len": pred_len,
        "dataset": dataset, "target_space": target_space,
        "train_end_date": str(all_dates[num_train - 1]),
        "date_range": f"{ref_dates[0]} → {ref_dates[-1]}",
    }
    return trues, persist, ref_dates, meta


# ─── Loaders ──────────────────────────────────────────────────────────────────

def load_flat(path: str, n_iv: int) -> np.ndarray:
    arr = np.load(path).astype(np.float32)
    if arr.ndim != 3 or arr.shape[-1] != n_iv:
        raise ValueError(f"Expected [N, pred, {n_iv}], got {arr.shape}")
    return arr


def load_hot(path: str, n_iv: int) -> np.ndarray:
    """
    HOT saves [N, H, W, pred_len] where (H, W) = (n_moneyness, n_tau).
    HOT script reshapes input via `iv.reshape(-1, H, W, order='F')` so that
    `grid[i_m, i_t] = csv col i_t·H + i_m`. The mirror F-order reshape here
    recovers the flat CSV column order:
        arr.transpose(0, 3, 1, 2)             → [N, pred, H, W]
        arr.reshape(N, pred, H*W, order='F')  → result[..., k] = grid[i_m, i_t]
                                                with k = i_m + H·i_t = csv col ✓
    """
    arr = np.load(path).astype(np.float32)
    if arr.ndim != 4:
        raise ValueError(f"Expected HOT [N, H, W, pred], got {arr.shape}")
    n, h, w, p = arr.shape
    if h * w != n_iv:
        raise ValueError(f"HOT grid {h}×{w}={h*w} ≠ {n_iv}")
    arr = arr.transpose(0, 3, 1, 2)
    return arr.reshape(n, p, h * w, order="F")


LOADERS = {"flat": load_flat, "hot": load_hot}


# ─── Date alignment ───────────────────────────────────────────────────────────

def align_to_ref(pred: np.ndarray, pred_dates: np.ndarray,
                 ref_dates: np.ndarray, name: str) -> np.ndarray:
    pred_dates = pred_dates.astype("datetime64[D]")
    date_to_idx = {d: i for i, d in enumerate(pred_dates)}
    indices, missing = [], []
    for d in ref_dates:
        i = date_to_idx.get(d)
        if i is None:
            missing.append(str(d))
        else:
            indices.append(i)
    if missing:
        raise ValueError(
            f"{name}: {len(missing)}/{len(ref_dates)} reference dates not in pred "
            f"(first missing: {missing[0]})"
        )
    return pred[np.array(indices)]


# ─── Metrics ──────────────────────────────────────────────────────────────────

def _lsts_components(pred: np.ndarray, true: np.ndarray,
                     moneyness: np.ndarray, tau: np.ndarray) -> dict:
    """LSTS components computed on a (..., n_tau, n_k) reshape of the flat
    n_iv-column predictions. Inputs are float32 numpy of shape [B, n_iv]
    (B can be N*P, or just N for a single horizon)."""
    n_m, n_t = len(moneyness), len(tau)
    pred_g = pred.reshape(-1, n_t, n_m)
    true_g = true.reshape(-1, n_t, n_m)
    p_t = torch.from_numpy(pred_g)
    t_t = torch.from_numpy(true_g)
    k_t = torch.from_numpy(moneyness)
    tau_t = torch.from_numpy(tau)
    comps = compute_lsts_components(p_t, t_t, k_t, tau_t)
    return {f"lsts_{k}": float(v.detach().cpu()) for k, v in comps.items()}


def compute_metrics(pred: np.ndarray, true: np.ndarray,
                    moneyness: np.ndarray, tau: np.ndarray,
                    origin: np.ndarray, target_space: str) -> dict:
    """
    pred, true, origin: [N, pred_len, n_iv] in original target-space units.
    `origin` is the forecast origin (last input value, broadcast across the
    horizon) — used to convert level predictions to changes for IC.
    `target_space` decides what IC ranks: 'level' subtracts origin (so IC ranks
    cells by forecast change in IV); 'logdiff' uses raw values (logdiffs are
    already changes, so the raw rank IS the cross-sectional direction signal).
    Returns scalar metrics plus per-horizon arrays (keyed with '_' prefix).
    """
    diff  = pred - true
    sq    = diff * diff
    abs_d = np.abs(diff)

    mse_v  = float(np.mean(sq))
    rmse_v = float(np.sqrt(mse_v))
    mae_v  = float(np.mean(abs_d))

    t64 = true.astype(np.float64)
    p64 = pred.astype(np.float64)
    rse_v = float(
        np.sqrt(np.sum((t64 - p64) ** 2))
        / np.sqrt(np.sum((t64 - t64.mean()) ** 2))
    )

    bias_v = float(np.mean(diff))
    da_v   = float(np.mean(np.sign(pred) == np.sign(true)))

    # Spearman rank-IC across the surface, per (window, step).
    # level   : rank-correlate predicted vs true CHANGES from forecast origin.
    #           Persistence (pred==origin) → constant zero → NaN by design.
    # logdiff : rank-correlate raw values (logdiffs are already changes; the
    #           raw cross-sectional rank IS the direction signal we want).
    if target_space == "level":
        pred_for_ic = pred - origin
        true_for_ic = true - origin
    elif target_space == "logdiff":
        pred_for_ic = pred
        true_for_ic = true
    else:
        raise ValueError(f"Unknown target_space {target_space!r}")

    N, P, F = pred.shape
    ic = np.full((N, P), np.nan)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", ConstantInputWarning)
        for i in range(N):
            for t in range(P):
                r, _ = spearmanr(pred_for_ic[i, t], true_for_ic[i, t])
                ic[i, t] = r if np.isfinite(r) else np.nan

    with warnings.catch_warnings():
        # Persist(ref) → IC array is all-NaN; nanmean warns "Mean of empty slice".
        warnings.simplefilter("ignore", RuntimeWarning)
        ic_mean_v = float(np.nanmean(ic))
        ic_std_v  = float(np.nanstd(ic))
        per_h_ic  = np.nanmean(ic, axis=0)

    per_h_mse = np.mean(sq,    axis=(0, 2))
    per_h_mae = np.mean(abs_d, axis=(0, 2))

    # LSTS — overall (averaged across all windows × horizons × surface cells).
    overall_lsts = _lsts_components(pred.reshape(-1, F), true.reshape(-1, F),
                                    moneyness, tau)

    # Per-horizon LSTS arrays.
    per_h_lsts = {f"lsts_{k}": np.empty(P, dtype=np.float64)
                  for k in ("level", "skew", "term", "curvature")}
    for h in range(P):
        comp = _lsts_components(pred[:, h, :], true[:, h, :], moneyness, tau)
        for k, v in comp.items():
            per_h_lsts[k][h] = v

    out = {
        "mse": mse_v, "rmse": rmse_v, "mae": mae_v, "rse": rse_v,
        "bias": bias_v, "da": da_v,
        "ic_mean": ic_mean_v, "ic_std": ic_std_v,
        "_per_h_mse": per_h_mse,
        "_per_h_mae": per_h_mae,
        "_per_h_ic":  per_h_ic,
    }
    out.update(overall_lsts)
    for k, arr in per_h_lsts.items():
        out[f"_per_h_{k}"] = arr
    return out


# ─── Display ──────────────────────────────────────────────────────────────────

OVERALL_COLS = ["mse", "rmse", "mae", "rse", "bias", "da",
                "ic_mean", "ic_std",
                "lsts_level", "lsts_skew", "lsts_term", "lsts_curvature"]
COL_FMT = {
    "mse": ".6f", "rmse": ".6f", "mae": ".6f", "rse": ".6f",
    "bias": "+.6f", "da": ".4f", "ic_mean": "+.4f", "ic_std": ".4f",
    "lsts_level":     ".4e",
    "lsts_skew":      ".4e",
    "lsts_term":      ".4e",
    "lsts_curvature": ".4e",
}


def _fmt(val: float, cw: int, fmt: str) -> str:
    if fmt.startswith("+"):
        return format(val, f">+{cw}{fmt[1:]}")
    return format(val, f">{cw}{fmt}")


def _col_width(results: list[dict]) -> int:
    return max(14, max(len(r["name"]) for r in results) + 2)


def print_summary(results: list[dict], pred_len: int):
    cw = _col_width(results)
    rw = 14
    names = [r["name"] for r in results]
    horizons = [h for h in REPORT_HORIZONS if h <= pred_len]

    sep   = "=" * (rw + 1 + cw * len(names))
    hdash = "-" * (rw + 1 + cw * len(names))

    print(f"\n{sep}")
    print(f"{'Metric':<{rw}} " + "".join(f"{n:>{cw}}" for n in names))
    print(sep)
    for m in OVERALL_COLS:
        fmt = COL_FMT[m]
        row = f"{m:<{rw}} " + "".join(_fmt(r[m], cw, fmt) for r in results)
        print(row)
    print(sep)

    n_ref = results[0]["n_windows"]
    print(f"\nPer-horizon Spearman IC  (N={n_ref} reference windows):")
    print(f"{'h':<{rw}}" + "".join(f"{n:>{cw}}" for n in names))
    print(hdash)
    for h in horizons:
        idx = h - 1
        row = f"t+{h:<{rw-2}}" + "".join(_fmt(r["_per_h_ic"][idx], cw, "+.4f") for r in results)
        print(row)

    print(f"\nPer-horizon MSE:")
    print(f"{'h':<{rw}}" + "".join(f"{n:>{cw}}" for n in names))
    print(hdash)
    for h in horizons:
        idx = h - 1
        row = f"t+{h:<{rw-2}}" + "".join(_fmt(r["_per_h_mse"][idx], cw, ".6f") for r in results)
        print(row)

    for comp in ("level", "skew", "term", "curvature"):
        key = f"_per_h_lsts_{comp}"
        print(f"\nPer-horizon LSTS {comp}:")
        print(f"{'h':<{rw}}" + "".join(f"{n:>{cw}}" for n in names))
        print(hdash)
        for h in horizons:
            idx = h - 1
            row = f"t+{h:<{rw-2}}" + "".join(_fmt(r[key][idx], cw, ".4e") for r in results)
            print(row)
    print()


# ─── Save ─────────────────────────────────────────────────────────────────────

def save_results(results: list[dict], out_dir: str, dataset: str,
                 target_space: str, seq_len: int, pred_len: int):
    os.makedirs(out_dir, exist_ok=True)
    ts  = datetime.now().strftime("%Y%m%d_%H%M%S")
    tag = f"{dataset}_{target_space}_sl{seq_len}_pl{pred_len}"

    scalar_rows = [
        {k: v for k, v in r.items() if not k.startswith("_")}
        for r in results
    ]
    df_overall = pd.DataFrame(scalar_rows)
    df_overall.to_csv(os.path.join(out_dir, f"{tag}_{ts}.csv"), index=False)
    df_overall.to_csv(os.path.join(out_dir, f"latest_{tag}.csv"), index=False)

    h_rows = []
    for r in results:
        for h in range(1, pred_len + 1):
            h_rows.append({
                "model":           r["name"],
                "horizon":         h,
                "ic":              r["_per_h_ic"][h - 1],
                "mse":             r["_per_h_mse"][h - 1],
                "mae":             r["_per_h_mae"][h - 1],
                "lsts_level":      r["_per_h_lsts_level"][h - 1],
                "lsts_skew":       r["_per_h_lsts_skew"][h - 1],
                "lsts_term":       r["_per_h_lsts_term"][h - 1],
                "lsts_curvature":  r["_per_h_lsts_curvature"][h - 1],
            })
    pd.DataFrame(h_rows).to_csv(
        os.path.join(out_dir, f"latest_horizons_{tag}.csv"), index=False)

    summary = {
        "timestamp":    ts,
        "dataset":      dataset,
        "target_space": target_space,
        "seq_len":      seq_len,
        "pred_len":     pred_len,
        "models": {
            r["name"]: {k: v for k, v in r.items() if not k.startswith("_")}
            for r in results
        },
    }
    with open(os.path.join(out_dir, f"latest_summary_{tag}.json"), "w") as f:
        json.dump(summary, f, indent=2)

    print(f"Saved to {out_dir}/  (tagged {tag})")


def write_per_model_metrics(model_dir: str, name: str, dataset: str,
                            target_space: str, seq_len: int, pred_len: int, m: dict):
    """Write a self-describing metrics_test.json into the model's result dir."""
    payload = {
        "model":        name,
        "dataset":      dataset,
        "target_space": target_space,
        "seq_len":      seq_len,
        "pred_len":     pred_len,
        "n_windows":    m["n_windows"],
        "metrics":    {k: v for k, v in m.items()
                       if not k.startswith("_") and k not in ("name", "n_windows", "source")},
        "per_horizon": {
            f"t+{h}": {
                "ic":              float(m["_per_h_ic"][h - 1]),
                "mse":             float(m["_per_h_mse"][h - 1]),
                "mae":             float(m["_per_h_mae"][h - 1]),
                "lsts_level":      float(m["_per_h_lsts_level"][h - 1]),
                "lsts_skew":       float(m["_per_h_lsts_skew"][h - 1]),
                "lsts_term":       float(m["_per_h_lsts_term"][h - 1]),
                "lsts_curvature":  float(m["_per_h_lsts_curvature"][h - 1]),
            }
            for h in REPORT_HORIZONS if h <= pred_len
        },
        "timestamp": datetime.now().strftime("%Y%m%d_%H%M%S"),
    }
    with open(os.path.join(model_dir, "metrics_test.json"), "w") as f:
        json.dump(payload, f, indent=2)


# ─── Resolution + regen ───────────────────────────────────────────────────────

def _config_n_iv_matches(cfg_path: str, expected_n_iv: int | None) -> bool:
    """If expected_n_iv is given, only accept dirs whose config.json `n_iv`
    matches the current CSV. Lets stale tuning dirs from a different grid
    (e.g. previous 20x20=400) be skipped automatically."""
    if expected_n_iv is None:
        return True
    try:
        with open(cfg_path) as f:
            cfg = json.load(f)
    except Exception:
        return False
    return int(cfg.get("n_iv", -1)) == int(expected_n_iv)


def _resolve_best_combo(tuning_dir: str, name: str,
                        expected_n_iv: int | None = None) -> str | None:
    """
    Read `<tuning_dir>/leaderboard.csv` and pick the lowest-val_loss combo
    that has both config.json and best_model.pt (and matches expected_n_iv
    when provided).
    """
    lb_path = os.path.join(tuning_dir, "leaderboard.csv")
    if not os.path.exists(lb_path):
        return None
    df = pd.read_csv(lb_path)
    if "best_val_loss" not in df.columns or "combo_id" not in df.columns:
        print(f"  {name}: leaderboard at {lb_path} missing required columns")
        return None
    df = df.dropna(subset=["best_val_loss"]).sort_values("best_val_loss")
    skipped_shape = 0
    for _, row in df.iterrows():
        cid = row["combo_id"]
        d = os.path.join(tuning_dir, cid)
        cfg  = os.path.join(d, "config.json")
        ckpt = os.path.join(d, "best_model.pt")
        if not (os.path.exists(cfg) and os.path.exists(ckpt)):
            continue
        if not _config_n_iv_matches(cfg, expected_n_iv):
            skipped_shape += 1
            continue
        print(f"  {name}: tuning best = {cid} "
              f"(val_loss={row['best_val_loss']:.6f}) at {d}")
        return d
    if skipped_shape:
        print(f"  {name}: {skipped_shape} combo(s) under {tuning_dir} "
              f"skipped (n_iv != {expected_n_iv}); will try result_dir")
    else:
        print(f"  {name}: no combo under {tuning_dir} has both config.json and best_model.pt")
    return None


def _resolve_result_dir(result_glob: str, requires_ckpt: bool, name: str,
                        expected_n_iv: int | None = None) -> str | None:
    """Glob `result_glob` and return the most-recently-modified dir that has
    config.json (and best_model.pt when `requires_ckpt`), filtered by
    expected_n_iv when provided. VAR has no checkpoint — refits from
    CSV+config in seconds."""
    matches = glob.glob(result_glob)
    if not matches:
        return None
    candidates = []
    for d in matches:
        cfg  = os.path.join(d, "config.json")
        ckpt = os.path.join(d, "best_model.pt")
        if not (os.path.exists(cfg) and (not requires_ckpt or os.path.exists(ckpt))):
            continue
        if not _config_n_iv_matches(cfg, expected_n_iv):
            continue
        candidates.append((d, os.path.getmtime(cfg)))
    if not candidates:
        return None
    d = max(candidates, key=lambda t: t[1])[0]
    print(f"  {name}: result dir = {d}")
    return d


def _is_var(spec: dict) -> bool:
    return "VAR/" in spec.get("regen_script", "")


def _maybe_regen(spec: dict, name: str, infer_batch: int,
                 expected_n_iv: int | None = None) -> str | None:
    out_dir = None
    if spec.get("tuning_dir"):
        out_dir = _resolve_best_combo(spec["tuning_dir"], name, expected_n_iv)
    if out_dir is None and spec.get("result_dir"):
        out_dir = _resolve_result_dir(spec["result_dir"],
                                      requires_ckpt=not _is_var(spec),
                                      name=name,
                                      expected_n_iv=expected_n_iv)
    if out_dir is None:
        return None

    pred_path = os.path.join(out_dir, "pred.npy")
    if os.path.exists(pred_path):
        print(f"  {name}: using existing pred.npy at {out_dir}")
        return pred_path

    cmd = [sys.executable, spec["regen_script"],
           "--predict_only", "--out_dir", out_dir]
    if not _is_var(spec):
        cmd.extend(["--batch_size", str(infer_batch)])
    print(f"  {name}: pred.npy missing → regenerating from {out_dir} ...")
    rc = subprocess.run(cmd).returncode
    if rc != 0 or not os.path.exists(pred_path):
        print(f"  {name}: regeneration failed (exit {rc})")
        return None
    print(f"  {name}: regenerated pred.npy")
    return pred_path


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Compare SPX IV forecasting models")
    parser.add_argument("--csv_path", default="SPX_surfaces.csv")
    parser.add_argument("--dataset",  default=DEFAULT_DATASET, choices=DATASET_CHOICES)
    parser.add_argument("--target_space", default=DEFAULT_TARGET_SPACE,
                        choices=TARGET_SPACE_CHOICES)
    parser.add_argument("--seq_len",  type=int, default=DEFAULT_SEQ_LEN)
    parser.add_argument("--pred_len", type=int, default=DEFAULT_PRED_LEN)
    parser.add_argument("--infer_batch", type=int, default=DEFAULT_INFER_BATCH,
                        help="Inference batch size when regenerating pred.npy. "
                             "Defaults to 32 (local-friendly), independent of "
                             "the (possibly larger) training batch.")
    parser.add_argument("--out_dir",  default="comparison_results")
    parser.add_argument("--models",   nargs="*", default=None,
                        help="Filter by case-insensitive name prefix "
                             "(e.g. --models DLinear HOT). Default: all.")
    args = parser.parse_args()

    models_for_run = build_models(args.dataset, args.target_space,
                                  args.seq_len, args.pred_len)
    if args.models:
        keep = [m.lower() for m in args.models]
        models_for_run = [
            spec for spec in models_for_run
            if any(spec["name"].lower().startswith(k) for k in keep)
        ]
        kept_names = [s["name"] for s in models_for_run]
        print(f"Model filter --models {args.models} → {kept_names}")
        if not models_for_run:
            print("No models match the filter; nothing to do.")
            return

    print(f"Building reference ground truth "
          f"(dataset={args.dataset}, target_space={args.target_space}, "
          f"seq_len={args.seq_len}, pred_len={args.pred_len})...")
    trues, persist, ref_dates, meta = build_reference(
        args.csv_path, dataset=args.dataset, target_space=args.target_space,
        seq_len=args.seq_len, pred_len=args.pred_len,
    )
    n_iv = meta["n_iv"]
    moneyness, tau = meta["moneyness"], meta["tau"]
    print(f"  T={meta['T']}, n_iv={n_iv}  "
          f"({meta['n_moneyness']} moneyness × {meta['n_tau']} tau), "
          f"train ends {meta['train_end_date']}")
    print(f"  test windows={meta['n_test']}, {meta['date_range']}")
    print(f"  inference batch (regen only): {args.infer_batch}")

    results = []

    m = compute_metrics(persist, trues, moneyness, tau,
                        origin=persist, target_space=args.target_space)
    m["name"] = "Persist(ref)"
    m["n_windows"] = meta["n_test"]
    m["source"] = "built-in"
    results.append(m)
    print(f"  Persist(ref): OK ({meta['n_test']} windows)")

    for spec in models_for_run:
        name = spec["name"]
        pred_path = _maybe_regen(spec, name, args.infer_batch,
                                 expected_n_iv=n_iv)
        if pred_path is None:
            print(f"  {name}: no regen-eligible dir for dataset={args.dataset!r}, "
                  f"target_space={args.target_space!r} — skipping")
            continue

        sibling_dates = os.path.join(os.path.dirname(pred_path), "start_dates.npy")
        dates_path = sibling_dates if os.path.exists(sibling_dates) else None

        try:
            pred = LOADERS[spec["loader"]](pred_path, n_iv)
        except Exception as e:
            print(f"  {name}: load error — {e}")
            continue

        if dates_path is not None:
            pred_dates = np.load(dates_path).astype("datetime64[D]")
            try:
                pred = align_to_ref(pred, pred_dates, ref_dates, name)
            except ValueError as e:
                print(f"  {name}: date alignment failed — {e}")
                continue
            n_windows = len(ref_dates)
            true_aligned    = trues
            persist_aligned = persist
        else:
            n_windows = min(len(pred), len(trues))
            if n_windows < len(trues):
                print(
                    f"  {name}: WARNING — no start_dates.npy; assuming sequential "
                    f"alignment from window 0 (model has {len(pred)}, ref has {len(trues)})."
                )
            pred = pred[:n_windows]
            true_aligned    = trues[:n_windows]
            persist_aligned = persist[:n_windows]

        if pred.shape[1:] != (args.pred_len, n_iv):
            print(f"  {name}: unexpected pred shape {pred.shape} — skipping")
            continue

        m = compute_metrics(pred, true_aligned, moneyness, tau,
                            origin=persist_aligned,
                            target_space=args.target_space)
        m["name"] = name
        m["n_windows"] = n_windows
        m["source"] = pred_path
        results.append(m)
        write_per_model_metrics(os.path.dirname(pred_path), name, args.dataset,
                                args.target_space, args.seq_len, args.pred_len, m)
        print(f"  {name}: OK ({n_windows} windows, {pred_path})")

    if len(results) == 1:
        print("\nOnly baseline available — nothing to compare.")
        return

    print_summary(results, args.pred_len)
    save_results(results, args.out_dir, args.dataset, args.target_space,
                 args.seq_len, args.pred_len)


if __name__ == "__main__":
    main()
