#!/usr/bin/env python3
"""
Benchmark comparison of SPX IV surface forecasting models.

Ground truth is built directly from SPX_surfaces.csv using the canonical
70/10/20 train/val/test split (same formula every standalone script uses).

Dataset selection:
    --dataset full      use the full CSV (default).
    --dataset precovid  slice the CSV to date <= 2019-12-31 before splitting.
                        The 70/10/20 split is computed on the slice.

For every entry in MODELS the result dir is resolved in this order:
  1. If `tuning_dir` is set, read `<tuning_dir>/leaderboard.csv` and pick the
     combo with the lowest `best_val_loss` whose directory has both
     `config.json` and `best_model.pt`. This is the canonical "best-of-tuning"
     source for hyperparameter-swept runs.
  2. Else (or if step 1 finds no usable combo), fall back to the `regen_dir`
     glob and pick the most-recently-modified match.

Once a directory is chosen, if `pred.npy` is present it is loaded; otherwise
it is regenerated by running `<regen_script> --predict_only --out_dir <dir>`,
which reads config.json + best_model.pt (or for VAR, just config.json, re-fits
in ~2 seconds) and writes pred.npy alongside.

All model scripts denormalize predictions to ORIGINAL target-space units
(raw IV for level; raw log-diff for logdiff) before saving pred.npy. The
reference trues/persist built here are in the same original space — so all
metrics below are in original units (vol-points for level).
Each model's start_dates.npy aligns its windows to the reference test set;
models with mismatched window counts will fail date alignment loudly.

Persistence baseline: built fresh from the CSV inside build_reference()
(`Persist(ref)` row in the table). Not a separate model entry.

Per-model side-effect: `metrics_test.json` is written into each model's
result dir alongside pred.npy, so a single model's scores can be inspected
without rebuilding the whole table.

Metrics (all in original target-space units — vol-points for level,
raw log-diff for logdiff):
  mse, rmse, mae, rse   standard regression metrics
  bias                  mean signed error; positive = over-prediction
  da                    directional accuracy: fraction where sign(pred)==sign(true)
  ic_mean, ic_std       Spearman rank-IC averaged across (window, step) over N_IV features

Outputs saved to --out_dir (default: comparison_results/):
  {dataset}_sl{sl}_pl{pl}_{ts}.csv   timestamped overall metrics
  latest_{dataset}_sl{sl}_pl{pl}.csv always overwritten with most recent run
  latest_horizons_{dataset}_sl{sl}_pl{pl}.csv per-horizon ic/mse/mae for every model
  latest_summary_{dataset}_sl{sl}_pl{pl}.json machine-readable summary
"""

import argparse
import glob
import json
import os
import subprocess
import sys
from datetime import datetime

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

# ─── Constants ────────────────────────────────────────────────────────────────

DEFAULT_SEQ_LEN      = 21
DEFAULT_PRED_LEN     = 63
TRAIN_FRAC           = 0.70
TEST_FRAC            = 0.20
PRECOVID_END         = "2019-12-31"
DATASET_CHOICES      = ["full", "precovid"]
TARGET_SPACE_CHOICES = ["level", "logdiff"]
REPORT_HORIZONS      = [1, 5, 10, 21, 42, 63]   # filtered to ≤ pred_len at use sites

# ─── Model registry ───────────────────────────────────────────────────────────
# Resolution order per model spec (see _maybe_regen):
#   1. If `tuning_dir` is set, read `<tuning_dir>/leaderboard.csv` and pick the
#      combo with the lowest `best_val_loss` whose dir has config.json +
#      best_model.pt. This is the canonical "best-of-tuning" source.
#   2. Else (or if step 1 finds nothing), fall back to the `regen_dir` glob.
#      Loss variants are append-suffixed and filtered via `name_filter`;
#      most-recently-modified match wins.
#   3. If no candidate dir is found → skip the model (do NOT silently fall back
#      to legacy paths).
#
# Once a directory is chosen, if pred.npy is present it is loaded; otherwise
# it is regenerated via `<regen_script> --predict_only --out_dir <dir>`.
#
# Persistence is not listed: `Persist(ref)` is built fresh from the CSV inside
# build_reference(), which is exactly the persistence baseline.
#
# Path conventions:
#   tuning_dir  → MODEL/tuning_results/{tag}[/variant]   (parent of leaderboard.csv)
#   regen_dir   → MODEL/results/{tag}_MODEL_*            (glob over finalized runs)

def build_models(dataset: str, target_space: str,
                 seq_len: int, pred_len: int) -> list[dict]:
    tag = f"{dataset}_{target_space}_SPX_IV_{seq_len}_{pred_len}"
    return [
        {
            "name":         "VAR(BIC)",
            "regen_dir":    f"VAR/results/{tag}_VAR_p*_bic",
            "regen_script": "VAR/var_spx_iv.py",
            "loader":       "flat",
        },
        {
            "name":         "VAR(AIC)",
            "regen_dir":    f"VAR/results/{tag}_VAR_p*_aic",
            "regen_script": "VAR/var_spx_iv.py",
            "loader":       "flat",
        },
        {
            "name":         "VAR(HQIC)",
            "regen_dir":    f"VAR/results/{tag}_VAR_p*_hqic",
            "regen_script": "VAR/var_spx_iv.py",
            "loader":       "flat",
        },
        {
            "name":         "DLinear",
            "tuning_dir":   f"DLinear/tuning_results/{tag}",
            "regen_dir":    f"DLinear/results/{tag}_DLinear_*",
            "name_filter":  lambda n: "_loss" not in n,
            "regen_script": "DLinear/dlinear.py",
            "loader":       "flat",
        },
        {
            "name":         "PatchTST",
            "regen_dir":    f"PatchTST/results/{tag}_PatchTST_*",
            "name_filter":  lambda n: "_loss" not in n and "_norevin" not in n,
            "regen_script": "PatchTST/patchtst.py",
            "loader":       "flat",
        },
        {
            "name":         "PatchTST(no-RevIN)",
            "regen_dir":    f"PatchTST/results/{tag}_PatchTST_*_norevin",
            "name_filter":  lambda n: "_loss" not in n,
            "regen_script": "PatchTST/patchtst.py",
            "loader":       "flat",
        },
        {
            "name":         "HOT(product)",
            "tuning_dir":   f"HOT/tuning_results/{tag}/kronecker_product",
            "regen_dir":    f"HOT/results/{tag}_HOT_tensor_*_kronecker_product*",
            "name_filter":  lambda n: "_loss" not in n and "_nonorm" not in n,
            "regen_script": "HOT/hot.py",
            "loader":       "hot",
        },
        {
            "name":         "HOT(prod,no-norm)",
            "regen_dir":    f"HOT/results/{tag}_HOT_tensor_*_kronecker_product*_nonorm",
            "name_filter":  lambda n: "_loss" not in n,
            "regen_script": "HOT/hot.py",
            "loader":       "hot",
        },
        {
            "name":         "HOT(sum)",
            "tuning_dir":   f"HOT/tuning_results/{tag}/kronecker_sum",
            "regen_dir":    f"HOT/results/{tag}_HOT_tensor_*_kronecker_sum*",
            "name_filter":  lambda n: "_loss" not in n and "_nonorm" not in n,
            "regen_script": "HOT/hot.py",
            "loader":       "hot",
        },
        {
            "name":         "HOT(sum,no-norm)",
            "regen_dir":    f"HOT/results/{tag}_HOT_tensor_*_kronecker_sum*_nonorm",
            "name_filter":  lambda n: "_loss" not in n,
            "regen_script": "HOT/hot.py",
            "loader":       "hot",
        },
        {
            "name":         "DynGWN",
            "tuning_dir":   f"DynGWN/tuning_results/{tag}/grid_plus_adaptive",
            "regen_dir":    f"DynGWN/results/{tag}_DynGWN_*",
            "name_filter":  lambda n: "_loss" not in n,    # default mse, no suffix
            "regen_script": "DynGWN/dyngwn.py",
            "loader":       "flat",
        },
        {
            "name":         "DynGWN(MAE-orig)",
            "regen_dir":    f"DynGWN/results/{tag}_DynGWN_*_lossmaeoriginal",
            "regen_script": "DynGWN/dyngwn.py",
            "loader":       "flat",
        },
        {
            "name":         "DynGWN(Hub-orig)",
            "regen_dir":    f"DynGWN/results/{tag}_DynGWN_*_losshuberoriginal_*",
            "regen_script": "DynGWN/dyngwn.py",
            "loader":       "flat",
        },
    ]


# ─── Ground truth ─────────────────────────────────────────────────────────────

def _slice_dataset(df: pd.DataFrame, dataset: str) -> pd.DataFrame:
    if dataset == "full":
        return df
    if dataset == "precovid":
        end = pd.Timestamp(PRECOVID_END)
        return df[df["date"] <= end].reset_index(drop=True)
    raise ValueError(f"Unknown dataset {dataset!r}; choose from {DATASET_CHOICES}")


def _apply_target_space(iv_raw: np.ndarray, dates_full: np.ndarray, target_space: str):
    """level → unchanged; logdiff → log(IV)[1:]-log(IV)[:-1], dates trimmed by 1."""
    if target_space == "level":
        return iv_raw, dates_full
    if target_space == "logdiff":
        if (iv_raw <= 0).any():
            raise ValueError("logdiff target_space requires all IV > 0")
        log_iv = np.log(iv_raw)
        return (log_iv[1:] - log_iv[:-1]).astype(iv_raw.dtype), dates_full[1:]
    raise ValueError(f"Unknown target_space {target_space!r}; choose from {TARGET_SPACE_CHOICES}")


def build_reference(csv_path: str, dataset: str, target_space: str,
                    seq_len: int, pred_len: int):
    """
    Returns:
      trues      [N, pred_len, n_iv] ground truth in ORIGINAL target-space
                 (raw IV for level; raw log-diff for logdiff). All model
                 scripts denormalize before saving pred.npy, so this matches.
      persist    [N, pred_len, n_iv] naive persistence baseline:
                   - level    → repeat last observed (original-space) value
                   - logdiff  → predict zero change (= level persistence after recon)
      ref_dates  [N] datetime64[D] start date of each prediction window
      meta       dict of split statistics (includes n_iv, target_space)
    """
    df = pd.read_csv(csv_path, low_memory=False)
    df["date"] = pd.to_datetime(df["date"])
    df = _slice_dataset(df, dataset)

    iv_cols = [c for c in df.columns if c.startswith("iv_")]
    if not iv_cols:
        raise ValueError(f"No iv_* columns found in {csv_path}")
    n_iv = len(iv_cols)

    iv_raw     = df[iv_cols].to_numpy(dtype=np.float32)
    dates_full = df["date"].to_numpy(dtype="datetime64[D]")
    data, all_dates = _apply_target_space(iv_raw, dates_full, target_space)

    T = len(data)
    num_train = int(T * TRAIN_FRAC)
    num_test  = int(T * TEST_FRAC)
    num_val   = T - num_train - num_test

    test_start = T - num_test - seq_len

    test_slice      = data[test_start:].astype(np.float32)
    test_date_slice = all_dates[test_start:]

    n = len(test_slice) - seq_len - pred_len + 1
    trues   = np.empty((n, pred_len, n_iv), dtype=np.float32)
    persist = np.empty((n, pred_len, n_iv), dtype=np.float32)
    ref_dates = np.empty(n, dtype="datetime64[D]")

    for i in range(n):
        trues[i] = test_slice[i + seq_len : i + seq_len + pred_len]
        if target_space == "logdiff":
            persist[i] = 0.0   # predict zero log-change (= level persistence)
        else:
            persist[i] = test_slice[i + seq_len - 1]
        ref_dates[i] = test_date_slice[i + seq_len]

    meta = {
        "T": T, "num_train": num_train, "num_val": num_val, "num_test": num_test,
        "n_iv": n_iv, "n_test": n,
        "seq_len": seq_len, "pred_len": pred_len,
        "dataset": dataset, "target_space": target_space,
        "train_end_date": str(all_dates[num_train - 1]),
        "date_range": f"{ref_dates[0]} → {ref_dates[-1]}",
    }
    return trues, persist, ref_dates, meta


# ─── Loaders ──────────────────────────────────────────────────────────────────

def load_flat(path: str, n_iv: int) -> np.ndarray:
    arr = np.load(path).astype(np.float32)
    if arr.ndim != 3 or arr.shape[-1] != n_iv:
        raise ValueError(f"Expected [N, pred, {n_iv}], got {arr.shape}")
    return arr


def load_hot(path: str, n_iv: int) -> np.ndarray:
    """
    HOT saves [N, H, W, pred_len] where (H, W) = (DELTA=17, TAU=10) for the
    170-cell layout. CSV column order is (T outer, D inner): col k = i_T·17 + i_D.

    The HOT script reshapes input via `iv.reshape(-1, 17, 10, order='F')` so that
    `grid[i_D, i_T] = col k`. The mirror F-order reshape here recovers the flat
    CSV column order:
        arr.transpose(0, 3, 1, 2) → [N, pred, H, W] = [N, pred, i_D, i_T]
        arr.reshape(N, pred, H*W, order='F') → result[..., k] = arr[..., i_D, i_T]
        with k = i_D + 17·i_T = i_T·17 + i_D = csv_col(i_T, i_D) ✓
    """
    arr = np.load(path).astype(np.float32)
    if arr.ndim != 4:
        raise ValueError(f"Expected HOT [N, H, W, pred], got {arr.shape}")
    n, h, w, p = arr.shape
    if h * w != n_iv:
        raise ValueError(f"HOT grid {h}×{w}={h*w} ≠ {n_iv}")
    arr = arr.transpose(0, 3, 1, 2)
    return arr.reshape(n, p, h * w, order="F")


LOADERS = {"flat": load_flat, "hot": load_hot}


# ─── Date alignment ───────────────────────────────────────────────────────────

def align_to_ref(pred: np.ndarray, pred_dates: np.ndarray,
                 ref_dates: np.ndarray, name: str) -> np.ndarray:
    pred_dates = pred_dates.astype("datetime64[D]")
    date_to_idx = {d: i for i, d in enumerate(pred_dates)}
    indices, missing = [], []
    for d in ref_dates:
        i = date_to_idx.get(d)
        if i is None:
            missing.append(str(d))
        else:
            indices.append(i)
    if missing:
        raise ValueError(
            f"{name}: {len(missing)}/{len(ref_dates)} reference dates not in pred "
            f"(first missing: {missing[0]})"
        )
    return pred[np.array(indices)]


# ─── Metrics ──────────────────────────────────────────────────────────────────

def compute_metrics(pred: np.ndarray, true: np.ndarray) -> dict:
    """
    pred, true: [N, pred_len, n_iv] in scaled space.

    Returns scalar metrics plus per-horizon arrays (keyed with '_' prefix).
    """
    diff  = pred - true
    sq    = diff * diff
    abs_d = np.abs(diff)

    mse_v  = float(np.mean(sq))
    rmse_v = float(np.sqrt(mse_v))
    mae_v  = float(np.mean(abs_d))

    t64 = true.astype(np.float64)
    p64 = pred.astype(np.float64)
    rse_v = float(
        np.sqrt(np.sum((t64 - p64) ** 2))
        / np.sqrt(np.sum((t64 - t64.mean()) ** 2))
    )

    bias_v = float(np.mean(diff))
    da_v   = float(np.mean(np.sign(pred) == np.sign(true)))

    N, P, F = pred.shape
    ic = np.full((N, P), np.nan)
    for i in range(N):
        for t in range(P):
            r, _ = spearmanr(pred[i, t], true[i, t])
            ic[i, t] = r if np.isfinite(r) else np.nan

    ic_mean_v = float(np.nanmean(ic))
    ic_std_v  = float(np.nanstd(ic))

    per_h_mse = np.mean(sq,    axis=(0, 2))
    per_h_mae = np.mean(abs_d, axis=(0, 2))
    per_h_ic  = np.nanmean(ic, axis=0)

    return {
        "mse": mse_v, "rmse": rmse_v, "mae": mae_v, "rse": rse_v,
        "bias": bias_v, "da": da_v,
        "ic_mean": ic_mean_v, "ic_std": ic_std_v,
        "_per_h_mse": per_h_mse,
        "_per_h_mae": per_h_mae,
        "_per_h_ic":  per_h_ic,
    }


# ─── Display ──────────────────────────────────────────────────────────────────

OVERALL_COLS = ["mse", "rmse", "mae", "rse", "bias", "da", "ic_mean", "ic_std"]
COL_FMT = {
    "mse": ".6f", "rmse": ".6f", "mae": ".6f", "rse": ".6f",
    "bias": "+.6f", "da": ".4f", "ic_mean": "+.4f", "ic_std": ".4f",
}


def _fmt(val: float, cw: int, fmt: str) -> str:
    if fmt.startswith("+"):
        return format(val, f">+{cw}{fmt[1:]}")
    return format(val, f">{cw}{fmt}")


def _col_width(results: list[dict]) -> int:
    return max(14, max(len(r["name"]) for r in results) + 2)


def print_summary(results: list[dict], pred_len: int):
    cw = _col_width(results)
    rw = 10
    names = [r["name"] for r in results]
    horizons = [h for h in REPORT_HORIZONS if h <= pred_len]

    sep   = "=" * (rw + 1 + cw * len(names))
    hdash = "-" * (rw + 1 + cw * len(names))

    print(f"\n{sep}")
    print(f"{'Metric':<{rw}} " + "".join(f"{n:>{cw}}" for n in names))
    print(sep)
    for m in OVERALL_COLS:
        fmt = COL_FMT[m]
        row = f"{m:<{rw}} " + "".join(_fmt(r[m], cw, fmt) for r in results)
        print(row)
    print(sep)

    n_ref = results[0]["n_windows"]
    print(f"\nPer-horizon Spearman IC  (N={n_ref} reference windows):")
    print(f"{'h':<8}" + "".join(f"{n:>{cw}}" for n in names))
    print(hdash)
    for h in horizons:
        idx = h - 1
        row = f"t+{h:<6}" + "".join(_fmt(r["_per_h_ic"][idx], cw, "+.4f") for r in results)
        print(row)

    print(f"\nPer-horizon MSE:")
    print(f"{'h':<8}" + "".join(f"{n:>{cw}}" for n in names))
    print(hdash)
    for h in horizons:
        idx = h - 1
        row = f"t+{h:<6}" + "".join(_fmt(r["_per_h_mse"][idx], cw, ".6f") for r in results)
        print(row)
    print()


# ─── Save ─────────────────────────────────────────────────────────────────────

def save_results(results: list[dict], out_dir: str, dataset: str,
                 target_space: str, seq_len: int, pred_len: int):
    """
    Filenames are tagged with `{dataset}_{target_space}_sl<sl>_pl<pl>` so
    different sweep configurations, datasets, and target spaces don't overwrite.
    """
    os.makedirs(out_dir, exist_ok=True)
    ts  = datetime.now().strftime("%Y%m%d_%H%M%S")
    tag = f"{dataset}_{target_space}_sl{seq_len}_pl{pred_len}"

    scalar_rows = [
        {k: v for k, v in r.items() if not k.startswith("_")}
        for r in results
    ]
    df_overall = pd.DataFrame(scalar_rows)
    df_overall.to_csv(os.path.join(out_dir, f"{tag}_{ts}.csv"), index=False)
    df_overall.to_csv(os.path.join(out_dir, f"latest_{tag}.csv"), index=False)

    h_rows = []
    for r in results:
        for h in range(1, pred_len + 1):
            h_rows.append({
                "model":   r["name"],
                "horizon": h,
                "ic":      r["_per_h_ic"][h - 1],
                "mse":     r["_per_h_mse"][h - 1],
                "mae":     r["_per_h_mae"][h - 1],
            })
    pd.DataFrame(h_rows).to_csv(
        os.path.join(out_dir, f"latest_horizons_{tag}.csv"), index=False)

    summary = {
        "timestamp":    ts,
        "dataset":      dataset,
        "target_space": target_space,
        "seq_len":      seq_len,
        "pred_len":     pred_len,
        "models": {
            r["name"]: {k: v for k, v in r.items() if not k.startswith("_")}
            for r in results
        },
    }
    with open(os.path.join(out_dir, f"latest_summary_{tag}.json"), "w") as f:
        json.dump(summary, f, indent=2)

    print(f"Saved to {out_dir}/  (tagged {tag})")


def write_per_model_metrics(model_dir: str, name: str, dataset: str,
                            target_space: str, seq_len: int, pred_len: int, m: dict):
    """Write a self-describing metrics_test.json into the model's result dir."""
    payload = {
        "model":        name,
        "dataset":      dataset,
        "target_space": target_space,
        "seq_len":      seq_len,
        "pred_len":     pred_len,
        "n_windows":    m["n_windows"],
        "metrics":    {k: v for k, v in m.items()
                       if not k.startswith("_") and k not in ("name", "n_windows", "source")},
        "per_horizon": {
            f"t+{h}": {
                "ic":  float(m["_per_h_ic"][h - 1]),
                "mse": float(m["_per_h_mse"][h - 1]),
                "mae": float(m["_per_h_mae"][h - 1]),
            }
            for h in REPORT_HORIZONS if h <= pred_len
        },
        "timestamp": datetime.now().strftime("%Y%m%d_%H%M%S"),
    }
    with open(os.path.join(model_dir, "metrics_test.json"), "w") as f:
        json.dump(payload, f, indent=2)


# ─── Main ─────────────────────────────────────────────────────────────────────

def _resolve_best_combo(tuning_dir: str, name: str) -> str | None:
    """
    Pick the best combo dir under `tuning_dir` by `best_val_loss` from
    `<tuning_dir>/leaderboard.csv`. Skips combos missing config.json or
    best_model.pt (e.g. discarded after tuning to save disk).

    Returns the absolute path to the chosen combo dir, or None if no usable
    combo is found.
    """
    lb_path = os.path.join(tuning_dir, "leaderboard.csv")
    if not os.path.exists(lb_path):
        return None
    df = pd.read_csv(lb_path)
    if "best_val_loss" not in df.columns or "combo_id" not in df.columns:
        print(f"  {name}: leaderboard at {lb_path} missing required columns")
        return None
    df = df.dropna(subset=["best_val_loss"]).sort_values("best_val_loss")
    for _, row in df.iterrows():
        cid = row["combo_id"]
        d = os.path.join(tuning_dir, cid)
        cfg  = os.path.join(d, "config.json")
        ckpt = os.path.join(d, "best_model.pt")
        if os.path.exists(cfg) and os.path.exists(ckpt):
            print(f"  {name}: tuning best = {cid} "
                  f"(val_loss={row['best_val_loss']:.6f}) at {d}")
            return d
    print(f"  {name}: no combo under {tuning_dir} has both config.json and best_model.pt")
    return None


def _resolve_regen_dir(spec: dict, name: str) -> str | None:
    """Glob `spec['regen_dir']` and return the most-recently-modified dir
    that has the required artefacts (config.json + best_model.pt for neural,
    config.json only for VAR). Returns None if nothing matches."""
    matches = glob.glob(spec["regen_dir"])
    name_filter = spec.get("name_filter")
    if name_filter is not None:
        matches = [d for d in matches if name_filter(os.path.basename(d.rstrip("/")))]
    if not matches:
        return None

    is_var = name.startswith("VAR")  # VAR has no checkpoint; refit from CSV+config in seconds
    candidates = []
    for d in matches:
        cfg  = os.path.join(d, "config.json")
        ckpt = os.path.join(d, "best_model.pt")
        if os.path.exists(cfg) and (is_var or os.path.exists(ckpt)):
            candidates.append((d, os.path.getmtime(cfg)))
    if not candidates:
        return None
    return max(candidates, key=lambda t: t[1])[0]


def _maybe_regen(spec: dict, name: str) -> str | None:
    """
    Resolve a model's pred.npy. Tries `tuning_dir` (leaderboard-aware) first,
    then falls back to the `regen_dir` glob. If pred.npy is already present in
    the chosen dir, use it; else regenerate via `--predict_only`.

    Returns the path to pred.npy if successful, else None.
    """
    out_dir = None
    if spec.get("tuning_dir"):
        out_dir = _resolve_best_combo(spec["tuning_dir"], name)
    if out_dir is None and spec.get("regen_dir"):
        out_dir = _resolve_regen_dir(spec, name)
        if out_dir is not None:
            print(f"  {name}: results dir = {out_dir}")
    if out_dir is None:
        return None

    pred_path = os.path.join(out_dir, "pred.npy")
    if os.path.exists(pred_path):
        print(f"  {name}: using existing pred.npy at {out_dir}")
        return pred_path

    print(f"  {name}: pred.npy missing → regenerating from {out_dir} ...")
    rc = subprocess.run(
        [sys.executable, spec["regen_script"], "--predict_only", "--out_dir", out_dir]
    ).returncode
    if rc != 0 or not os.path.exists(pred_path):
        print(f"  {name}: regeneration failed (exit {rc})")
        return None
    print(f"  {name}: regenerated pred.npy")
    return pred_path


def main():
    parser = argparse.ArgumentParser(description="Compare SPX IV forecasting models")
    parser.add_argument("--csv_path", default="SPX_surfaces.csv")
    parser.add_argument("--dataset",  default="full", choices=DATASET_CHOICES,
                        help="full = entire CSV; precovid = dates <= 2019-12-31")
    parser.add_argument("--target_space", default="level", choices=TARGET_SPACE_CHOICES,
                        help="level = compare on raw IV (default); logdiff = compare "
                             "on log(IV)[1:]-log(IV)[:-1]. Persist baseline becomes "
                             "predict-zero-change in logdiff space.")
    parser.add_argument("--seq_len",  type=int, default=DEFAULT_SEQ_LEN)
    parser.add_argument("--pred_len", type=int, default=DEFAULT_PRED_LEN)
    parser.add_argument("--out_dir",  default="comparison_results")
    parser.add_argument("--models",   nargs="*", default=None,
                        help="Filter models by case-insensitive name prefix "
                             "(e.g. --models DLinear HOT DynGWN keeps DLinear, "
                             "HOT(product), HOT(sum), DynGWN). Default: all.")
    args = parser.parse_args()

    models_for_run = build_models(args.dataset, args.target_space,
                                  args.seq_len, args.pred_len)
    if args.models:
        keep = [m.lower() for m in args.models]
        models_for_run = [
            spec for spec in models_for_run
            if any(spec["name"].lower().startswith(k) for k in keep)
        ]
        kept_names = [s["name"] for s in models_for_run]
        print(f"Model filter --models {args.models} → {kept_names}")
        if not models_for_run:
            print("No models match the filter; nothing to do.")
            return

    print(f"Building reference ground truth "
          f"(dataset={args.dataset}, target_space={args.target_space}, "
          f"seq_len={args.seq_len}, pred_len={args.pred_len})...")
    trues, persist, ref_dates, meta = build_reference(
        args.csv_path, dataset=args.dataset, target_space=args.target_space,
        seq_len=args.seq_len, pred_len=args.pred_len,
    )
    n_iv = meta["n_iv"]
    print(f"  T={meta['T']}, n_iv={n_iv}, train ends {meta['train_end_date']}")
    print(f"  test windows={meta['n_test']}, {meta['date_range']}")

    results = []

    m = compute_metrics(persist, trues)
    m["name"] = "Persist(ref)"
    m["n_windows"] = meta["n_test"]
    m["source"] = "built-in"
    results.append(m)
    print(f"  Persist(ref): OK ({meta['n_test']} windows)")

    for spec in models_for_run:
        name = spec["name"]
        pred_path = _maybe_regen(spec, name)
        if pred_path is None:
            print(f"  {name}: no regen-eligible dir for dataset={args.dataset!r}, "
                  f"target_space={args.target_space!r} — skipping")
            continue

        sibling_dates = os.path.join(os.path.dirname(pred_path), "start_dates.npy")
        dates_path = sibling_dates if os.path.exists(sibling_dates) else None

        try:
            pred = LOADERS[spec["loader"]](pred_path, n_iv)
        except Exception as e:
            print(f"  {name}: load error — {e}")
            continue

        if dates_path is not None:
            pred_dates = np.load(dates_path).astype("datetime64[D]")
            try:
                pred = align_to_ref(pred, pred_dates, ref_dates, name)
            except ValueError as e:
                print(f"  {name}: date alignment failed — {e}")
                continue
            n_windows = len(ref_dates)
            true_aligned = trues
        else:
            n_windows = min(len(pred), len(trues))
            if n_windows < len(trues):
                print(
                    f"  {name}: WARNING — no start_dates.npy; assuming sequential "
                    f"alignment from window 0 (model has {len(pred)}, ref has {len(trues)}). "
                )
            pred = pred[:n_windows]
            true_aligned = trues[:n_windows]

        if pred.shape[1:] != (args.pred_len, n_iv):
            print(f"  {name}: unexpected pred shape {pred.shape} — skipping")
            continue

        m = compute_metrics(pred, true_aligned)
        m["name"] = name
        m["n_windows"] = n_windows
        m["source"] = pred_path
        results.append(m)
        write_per_model_metrics(os.path.dirname(pred_path), name, args.dataset,
                                args.target_space, args.seq_len, args.pred_len, m)
        print(f"  {name}: OK ({n_windows} windows, {pred_path})")

    if len(results) == 1:
        print("\nOnly baseline available — nothing to compare.")
        return

    print_summary(results, args.pred_len)
    save_results(results, args.out_dir, args.dataset, args.target_space,
                 args.seq_len, args.pred_len)


if __name__ == "__main__":
    main()
